PROG = shape2ps triangle2shape shape2triangle amalgamate shapedump shape2xml

CC = /usr/local/intel/compiler70/ia32/bin/icc

INCLUDES = -I $(includedir) -I $(includedir)/newbase -I $(includedir)/imagine
CFLAGS = -DUNIX $(INCLUDES) -w2 -Werror -wd981,383,869,1418,810,444,488,279

LIBS = -L$(libdir) -limagine -lnewbase -ljpeg -lpng -lz

# Common library compiling template

include ../../makefiles/makefile.prog
