#!/bin/sh -x

# Convert shape to PSLG, removing all islands smaller than 5km2

shape2triangle 5 /var/www/share/shapes/DCW/Suomi/ponet suomi

# Triangulate it

triangle -pcAI suomi

# Accept distances smaller than 4km for amalgamation, and
# remove all islands which remain smaller than 100km2

amalgamate 4 100 suomi suomi.1

# Convert back to a shapefile, no area limit

triangle2shape 0 suomi.1 suomishape

# Optionally one may visualize the results

# triangleshow suomi

